[package]
name = "aoc202006"
version = "0.1.0"
authors = ["Matthew Gumport <m@gum.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
